### ISSUE TITLE
Is this possible for uploading files(.png, .xlsx, .pdf, .doc) to Slack ?

### ISSUE THREAD

**Issue by RemigiusL** [log4js-node/slack#4]
Is this possible for uploading files(.png, .xlsx, .pdf, .doc) to Slack!, could you help me out with help of configuration code.

**Comment by nomiddlename** [comment]
That's not really what this library is for. You're better off starting at the [Slack API docs](https://api.slack.com) if you want to build an app that sends files to Slack.

**Comment by RemigiusL** [comment]
@nomiddlename,
Ok, thanks for your great update.
